name: My First GitHub Action

on:
  push:

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
       - name: System Information
         run: |
          echo "Hello DevOps Engineer"
          date
          whoami
          pwd
          uname -a