name: My First GitHub Action

on:
  push:

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: |
         echo "Hello DevOps Engineer"
         echo "Welcome to GitHub Actions"
         echo "Today I am learning CI/CD"